# Сообщения
CREATE TABLE chat.e_messages
(
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES sysinfo.users(id),
	message_text TEXT NOT NULL,
	send_date TIMESTAMP WITH TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL 
);

# Задачи
CREATE TABLE open_project.e_tasks
(
	id SERIAL PRIMARY KEY,
	task_name VARCHAR(200) NOT NULL UNIQUE,
	task_description TEXT NOT NULL UNIQUE,
	create_date TIMESTAMP WITH TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL
);